name: James Benton
favicon: null
layout_spectrum: 0.8113356148824096
typography_spectrum: 0.5095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#adaaa2'
    - '#8f8b86'
    - '#4a4944'
    - '#61605c'
  brandStrength: 0.9597527377773076
  lightness: 0.3187076128087938
  saturation: 0.33613429800607264
  rhythmicContrast: 0.5
purpose: []
