name: James Benton
favicon: null
layout_spectrum: 0.49927
typography_spectrum: 0.5095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1e1d'
    - '#7e7470'
    - '#9e9890'
    - '#d1baa4'
    - '#914d4d'
  brandStrength: 0.9597527377773076
  lightness: 0.3187076128087938
  saturation: 0.33613429800607264
  rhythmicContrast: 0.5
purpose: []
